<?php
if (!isset($age)) $age = 137;
?>
<div class="paragraph">
	<span class="b">I am a <?= $age ?> ye</span>ar-<span class="b">ol</span>d <span class="b">Fr</span>ench <span class="b">stud</span>ent, <span class="b">cur</span>rently <span class="b">stud</span>ying <span class="b">in</span> <span class="b">Télé</span>com <span class="b">Nan</span>cy, <span class="b">aspir</span>ing <span class="b">t</span>o <span class="b">b</span>e <span class="b">a</span> <span class="b">comp</span>uter <span class="b">engin</span>eer.
	<span class="b">Bei</span>ng <span class="b">passi</span>onate <span class="b">ab</span>out <span class="b">comp</span>uter <span class="b">sci</span>ence, <span class="b">math</span>ematics <span class="b">an</span>d <span class="b">phy</span>sics, <span class="b">I am alw</span>ays <span class="b">look</span>ing <span class="b">f</span>or <span class="b">ne</span>w <span class="b">top</span>ics <span class="b">t</span>o <span class="b">disc</span>over <span class="b">an</span>d <span class="b">t</span>o <span class="b">lea</span>rn <span class="b">fr</span>om.
	<span class="b">In lo</span>ve <span class="b">wi</span>th <span class="b">cha</span>llenges, <span class="b">I li</span>ke <span class="b">t</span>o <span class="b">ta</span>ke <span class="b">o</span>n <span class="b">ne</span>w <span class="b">proj</span>ects <span class="b">an</span>d <span class="b">t</span>o <span class="b">lea</span>rn <span class="b">ne</span>w <span class="b">sk</span>ills.
	<span class="b">N</span>o <span class="b">mat</span>ter <span class="b">th</span>e <span class="b">fi</span>eld, <span class="b">I am al</span>ways <span class="b">look</span>ing <span class="b">f</span>or <span class="b">oppor</span>tunities <span class="b">t</span>o <span class="b">imp</span>rove <span class="b">mys</span>elf.
	<span class="b">Whet</span>her <span class="b">i</span>t <span class="b">i</span>s <span class="b">a</span> <span class="b">ha</span>rd <span class="b">top</span>ic <span class="b">o</span>r <span class="b">n</span>ot, <span class="b">I al</span>ways <span class="b">tr</span>y <span class="b">t</span>o <span class="b">fi</span>nd <span class="b">a wa</span>y <span class="b">t</span>o <span class="b">underst</span>and <span class="b">i</span>t.
	<span class="b">I am nev</span>er <span class="b">afr</span>aid <span class="b">t</span>o <span class="b">g</span>o <span class="b">ou</span>t <span class="b">o</span>f <span class="b">m</span>y <span class="b">hab</span>its <span class="b">an</span>d <span class="b">t</span>o <span class="b">tr</span>y <span class="b">t</span>o <span class="b">d</span>o <span class="b">thi</span>ngs <span class="b">diff</span>erently.
	<span class="b">A</span>s <span class="b">a qui</span>ck <span class="b">lea</span>rner, <span class="b">I ca</span>n <span class="b">eas</span>ily <span class="b">ada</span>pt <span class="b">t</span>o <span class="b">ne</span>w <span class="b">environ</span>ments.
	<span class="b">Wi</span>th <span class="b">a str</span>ong <span class="b">sen</span>se <span class="b">o</span>f <span class="b">responsib</span>ility, <span class="b">I am al</span>ways <span class="b">rea</span>dy <span class="b">t</span>o <span class="b">he</span>lp <span class="b">oth</span>ers <span class="b">an</span>d <span class="b">t</span>o <span class="b">gi</span>ve <span class="b">m</span>y <span class="b">be</span>st.
	<span class="b">Fin</span>ally, <span class="b">I am a ve</span>ry <span class="b">cur</span>ious <span class="b">pers</span>on, <span class="b">al</span>ways <span class="b">seek</span>ing <span class="b">fo</span>r <span class="b">ne</span>w <span class="b">thi</span>ngs <span class="b">t</span>o <span class="b">disc</span>over.
</div>
<div class="paragraph">
	<span class="b">I lo</span>ve <span class="b">play</span>ing <span class="b">mus</span>ical <span class="b">instrum</span>ents, <span class="b">su</span>ch <span class="b">a</span>s <span class="b">th</span>e <span class="b">pia</span>no, <span class="b">th</span>e <span class="b">guit</span>ar <span class="b">o</span>r <span class="b">ev</span>en <span class="b">th</span>e <span class="b">ba</span>ss.
	<span class="b">I</span>n <span class="b">add</span>ition, <span class="b">I somet</span>imes <span class="b">comp</span>ose <span class="b">m</span>y <span class="b">ow</span>n <span class="b">mus</span>ic, <span class="b">most</span>ly <span class="b">i</span>n <span class="b">th</span>e <span class="b">Fr</span>ench-<span class="b">tou</span>ch <span class="b">gen</span>re.
	<span class="b">Al</span>so, <span class="b">I am curr</span>ently <span class="b">learn</span>ing <span class="b">Ger</span>man <span class="b">a</span>s <span class="b">I am plan</span>ning <span class="b">t</span>o <span class="b">mo</span>ve <span class="b">t</span>o <span class="b">Ger</span>many <span class="b">i</span>n <span class="b">th</span>e <span class="b">fut</span>ure.
</div>