<?php
if (!isset($age)) $age = 137;
?>
<div class="paragraph">
	I <span class="b">a</span>m a <span class="b"><?= $age ?> y</span>ear-<span class="b">o</span>ld <span class="b">Fr</span>ench <span class="b">stud</span>ent, <span class="b">cur</span>rently <span class="b">stud</span>ying in <span class="b">Télé</span>com <span class="b">Nan</span>cy, <span class="b">aspir</span>ing to <span class="b">b</span>e a <span class="b">comp</span>uter <span class="b">engin</span>eer.
	<span class="b">Be</span>ing <span class="b">pas</span>sionate <span class="b">ab</span>out <span class="b">comp</span>uter <span class="b">sci</span>ence, <span class="b">math</span>ematics <span class="b">a</span>nd <span class="b">phy</span>sics, I <span class="b">a</span>m <span class="b">alw</span>ays <span class="b">look</span>ing for <span class="b">n</span>ew <span class="b">top</span>ics to <span class="b">disc</span>over <span class="b">a</span>nd to <span class="b">le</span>arn <span class="b">fr</span>om.
	<span class="b">I</span>n <span class="b">lo</span>ve <span class="b">w</span>ith <span class="b">cha</span>llenges, I <span class="b">li</span>ke to <span class="b">ta</span>ke <span class="b">o</span>n <span class="b">n</span>ew <span class="b">proj</span>ects <span class="b">a</span>nd to <span class="b">le</span>arn <span class="b">n</span>ew <span class="b">sk</span>ills.
	<span class="b">N</span>o <span class="b">mat</span>ter the <span class="b">fi</span>eld, I <span class="b">a</span>m <span class="b">alw</span>ays <span class="b">look</span>ing <span class="b">f</span>or <span class="b">opp</span>ortunities to <span class="b">imp</span>rove <span class="b">mys</span>elf.
	<span class="b">Whet</span>her it <span class="b">i</span>s a <span class="b">ha</span>rd <span class="b">top</span>ic <span class="b">o</span>r <span class="b">n</span>ot, I <span class="b">alw</span>ays <span class="b">t</span>ry to <span class="b">fi</span>nd a <span class="b">w</span>ay to <span class="b">underst</span>and it.
	I <span class="b">a</span>m <span class="b">nev</span>er <span class="b">afr</span>aid to <span class="b">g</span>o <span class="b">ou</span>t of my <span class="b">hab</span>its <span class="b">a</span>nd to <span class="b">tr</span>y to <span class="b">d</span>o <span class="b">thi</span>ngs <span class="b">diff</span>erently.
	<span class="b">A</span>s a <span class="b">qui</span>ck <span class="b">le</span>arner, I <span class="b">ca</span>n <span class="b">eas</span>ily <span class="b">ada</span>pt to <span class="b">n</span>ew <span class="b">environ</span>ments.
	<span class="b">Wi</span>th a <span class="b">str</span>ong <span class="b">sen</span>se of <span class="b">responsib</span>ility, I <span class="b">a</span>m <span class="b">alw</span>ays <span class="b">rea</span>dy to <span class="b">he</span>lp <span class="b">oth</span>ers <span class="b">a</span>nd to <span class="b">gi</span>ve <span class="b">m</span>y <span class="b">be</span>st.
	<span class="b">Fin</span>ally, I <span class="b">a</span>m a <span class="b">ve</span>ry <span class="b">cur</span>ious <span class="b">pe</span>rson, <span class="b">alw</span>ays <span class="b">seek</span>ing <span class="b">fo</span>r <span class="b">n</span>ew <span class="b">thi</span>ngs to <span class="b">disc</span>over.
</div>
<div class="paragraph">
	I <span class="b">lo</span>ve <span class="b">play</span>ing <span class="b">mus</span>ical <span class="b">instr</span>uments, <span class="b">su</span>ch <span class="b">a</span>s the <span class="b">pia</span>no, the <span class="b">gui</span>tar <span class="b">o</span>r <span class="b">ev</span>en the <span class="b">ba</span>ss.
	<span class="b">I</span>n <span class="b">add</span>ition, I <span class="b">somet</span>imes <span class="b">comp</span>ose <span class="b">m</span>y <span class="b">o</span>wn <span class="b">mus</span>ic, <span class="b">most</span>ly <span class="b">i</span>n the <span class="b">Fr</span>ench-<span class="b">tou</span>ch <span class="b">gen</span>re.
	<span class="b">Al</span>so, I <span class="b">a</span>m <span class="b">curr</span>ently <span class="b">learn</span>ing <span class="b">Ger</span>man <span class="b">a</span>s I <span class="b">a</span>m <span class="b">plan</span>ning to <span class="b">mo</span>ve to <span class="b">Ger</span>many <span class="b">i</span>n the <span class="b">fut</span>ure.
</div>